# Generated by Django 6.0.6 on 2026-09-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('orders', '0002_order_address_order_address_ref_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lead_minutes', models.PositiveIntegerField(default=120, help_text='Minimum minutes between ordering and the slot start (same-day orders).')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_slots', to='cities.city')),
            ],
            options={
                'ordering': ['city', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryslot'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='delivery_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='deliveryslot',
            constraint=models.UniqueConstraint(fields=('city', 'start_time', 'end_time'), name='delivery_slot_unique_window'),
        ),
    ]
