# Generated by Django 6.0.6 on 2026-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='step',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('sht', 'дона'), ('l', 'литр'), ('g', 'грамм'), ('boglam', 'боғлам')], default='kg', max_length=8),
        ),
    ]
