# Generated by Django 6.0.6 on 2026-06-07 12:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_step_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='step',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
